/// Address.dart
/// Version 0.0.1a
/// Copyright 2016 Programmers for a Better Tomorrow, Yesterday

part of entities;

/// Address
/// This is an autogenerated class mapping the MySQL Table Address to an AvacadORM Entity.

/// Subtype of Communication_Mechanism, this is a physical address in the USA. This could later be adapted to support international addresses as well, but currently does not.
@Table('Address')
class Address extends Entity {
	// ***Table Columns***
	@Column.PrimaryKey('id')
	int id;
	@Column('Communication_Mechanism_id')
	int Communication_Mechanism_id;
	@Column('street_address')
	String street_address;
	@Column('street_address_2')
	String street_address_2;
	@Column('city')
	String city;
	@Column('state')
	String state;
	@Column('zip')
	String zip;

	// ***Table Foreign Key Entities***
	@Column.ManyToOneForeignKey('Communication_Mechanism_id')
	Communication_Mechanism communication_mechanism;
	@Column.OneToManyForeignKey('Address_id')
	List<Shipment> shipments_from;
	@Column.OneToManyForeignKey('Address_id1')
	List<Shipment> shipments_to;
}
