/// Alternate_Search_String.dart
/// Version 0.0.1a
/// Copyright 2016 Programmers for a Better Tomorrow, Yesterday

part of entities;

/// Alternate_Search_String
/// This is an autogenerated class mapping the MySQL Table Alternate_Search_String to an AvacadORM Entity.

/// List of query keywords that should return the linked Good.
@Table('Alternate_Search_String')
class Alternate_Search_String extends Entity {
	// ***Table Columns***
	@Column.PrimaryKey('id')
	int id;
	@Column('Good_Identification_id')
	int Good_Identification_id;
	@Column('search_string')
	String search_string;

	// ***Table Foreign Key Entities***
	@Column.ManyToOneForeignKey('Good_Identification_id')
	Good_Identification good_identification;
}