/// Building.dart
/// Version 0.0.1a
/// Copyright 2016 Programmers for a Better Tomorrow, Yesterday

part of entities;

/// Building
/// This is an autogenerated class mapping the MySQL Table Building to an AvacadORM Entity.

/// Buildings are a subtype of facilities, representing physical buildings in meatspace.
@Table('Building')
class Building extends Entity {
	// ***Table Columns***
	@Column.PrimaryKey('id')
	int id;
	@Column('Facility_id')
	int Facility_id;

	// ***Table Foreign Key Entities***
	@Column.ManyToOneForeignKey('Facility_id')
	Facility facility;
}