/// Communication_Event_Role.dart
/// Version 0.0.1a
/// Copyright 2016 Programmers for a Better Tomorrow, Yesterday

part of entities;

/// Communication_Event_Role
/// This is an autogenerated class mapping the MySQL Table Communication_Event_Role to an AvacadORM Entity.

/// Used for >= 3-party communications to log each party involved in a Communication_Event and their respective roles in that event. The same party could also hold several roles in the event.
@Table('Communication_Event_Role')
class Communication_Event_Role extends Entity {
	// ***Table Columns***
	@Column.PrimaryKey('id')
	int id;
	@Column('Party_id')
	int Party_id;
	@Column('Communication_Event_id')
	int Communication_Event_id;
	@Column('Communication_Event_Role_Type_id')
	int Communication_Event_Role_Type_id;

	// ***Table Foreign Key Entities***
	@Column.ManyToOneForeignKey('Communication_Event_id')
	Communication_Event communication_event;
	@Column.ManyToOneForeignKey('Communication_Event_Role_Type_id')
	Communication_Event_Role_Type communication_event_role_type;
	@Column.ManyToOneForeignKey('Party_id')
	Party party;
}