/// Communication_Event_Role_Type.dart
/// Version 0.0.1a
/// Copyright 2016 Programmers for a Better Tomorrow, Yesterday

part of entities;

/// Communication_Event_Role_Type
/// This is an autogenerated class mapping the MySQL Table Communication_Event_Role_Type to an AvacadORM Entity.

/// List of roles to be referenced by a Communication_Event_Role entity
@Table('Communication_Event_Role_Type')
class Communication_Event_Role_Type extends Entity {
	// ***Table Columns***
	@Column.PrimaryKey('id')
	int id;
	@Column('description')
	String description;

	// ***Table Foreign Key Entities***
	@Column.OneToManyForeignKey('Communication_Event_Role_Type_id')
	List<Communication_Event_Role> communication_event_roles;
}