/// Communication_Mechanism.dart
/// Version 0.0.1a
/// Copyright 2016 Programmers for a Better Tomorrow, Yesterday

part of entities;

/// Communication_Mechanism
/// This is an autogenerated class mapping the MySQL Table Communication_Mechanism to an AvacadORM Entity.

/// A Communication_Mechanism is an object that allows connections and transfer of information to another Communication_Mechanism. Subtypes include email addresses, phone numbers, and physical addresses
@Table('Communication_Mechanism')
class Communication_Mechanism extends Entity {
	// ***Table Columns***
	@Column.PrimaryKey('id')
	int id;

	// ***Table Foreign Key Entities***
	@Column.OneToManyForeignKey('Communication_Mechanism_id')
	List<Email_Address> email_addresss;
	@Column.OneToManyForeignKey('Communication_Mechanism_id')
	List<Phone_Number> phone_numbers;
	@Column.OneToManyForeignKey('Communication_Mechanism_id')
	List<Address> addresss;
	@Column.OneToManyForeignKey('Communication_Mechanism_id')
	List<Party_Communication_Association> party_communication_associations;
	@Column.OneToManyForeignKey('Communication_Mechanism_id')
	List<Facility_Communication_Association> facility_communication_associations;
	@Column.OneToManyForeignKey('Communication_Mechanism_id')
	List<Order_Communication_Mechanism> order_communication_mechanisms;
	@Column.OneToManyForeignKey('Communication_Mechanism_id')
	List<Order_Item_Communication_Mechanism> order_item_communication_mechanisms;
}