/// Communication_Mechanism_Type.dart
/// Version 0.0.1a
/// Copyright 2016 Programmers for a Better Tomorrow, Yesterday

part of entities;

/// Communication_Mechanism_Type
/// This is an autogenerated class mapping the MySQL Table Communication_Mechanism_Type to an AvacadORM Entity.

/// List of types of Communication_Mechanism, to be referenced by Communication_Event entities. The actual mechanisms used are irrelevant, the associated Party_Relationship and Communication_Mechanism_Type provide all the important information about the communication event.
@Table('Communication_Mechanism_Type')
class Communication_Mechanism_Type extends Entity {
	// ***Table Columns***
	@Column.PrimaryKey('id')
	int id;
	@Column('description')
	String description;

	// ***Table Foreign Key Entities***
	@Column.OneToManyForeignKey('Communication_Mechanism_Type_id')
	List<Communication_Event> communication_events;
}