/// Communication_Mechanism_Purpose_Type.dart
/// Version 0.0.1a
/// Copyright 2016 Programmers for a Better Tomorrow, Yesterday

part of entities;

/// Communication_Mechanism_Purpose_Type
/// This is an autogenerated class mapping the MySQL Table Communication_Mechanism_Purpose_Type to an AvacadORM Entity.

/// Used to define the purpose of a given linked Communication_Mechanism.
@Table('Communication_Mechanism_Purpose_Type')
class Communication_Mechanism_Purpose_Type extends Entity {
	// ***Table Columns***
	@Column.PrimaryKey('id')
	int id;
	@Column('description')
	String description;

	// ***Table Foreign Key Entities***
	@Column.OneToManyForeignKey('Communication_Mechanism_Purpose_Type_id')
	List<Order_Communication_Mechanism> order_communication_mechanisms;
	@Column.OneToManyForeignKey('Communication_Mechanism_Purpose_Type_id')
	List<Order_Item_Communication_Mechanism> order_item_communication_mechanisms;
}