/// Contact.dart
/// Version 0.0.1a
/// Copyright 2016 Programmers for a Better Tomorrow, Yesterday

part of entities;

/// Contact
/// This is an autogenerated class mapping the MySQL Table Contact to an AvacadORM Entity.

/// Subclass of Person_Role that represents Contacts of the business.
@Table('Contact')
class Contact extends Entity {
	// ***Table Columns***
	@Column.PrimaryKey('id')
	int id;
	@Column('Person_Role_id')
	int Person_Role_id;

	// ***Table Foreign Key Entities***
	@Column.ManyToOneForeignKey('Person_Role_id')
	Person_Role person_role;
}