/// Cost_Product_Association.dart
/// Version 0.0.1a
/// Copyright 2016 Programmers for a Better Tomorrow, Yesterday

part of entities;

/// Cost_Product_Association
/// This is an autogenerated class mapping the MySQL Table Cost_Product_Association to an AvacadORM Entity.

/// Associates an Estimated_Product_Cost with a Product entity.
@Table('Cost_Product_Association')
class Cost_Product_Association extends Entity {
	// ***Table Columns***
	@Column.PrimaryKey('id')
	int id;
	@Column('Estimated_Product_Cost_id')
	int Estimated_Product_Cost_id;
	@Column('Product_id')
	int Product_id;

	// ***Table Foreign Key Entities***
	@Column.ManyToOneForeignKey('Estimated_Product_Cost_id')
	Estimated_Product_Cost estimated_product_cost;
	@Column.ManyToOneForeignKey('Product_id')
	Product product;
}