/// Cost_Component_Type.dart
/// Version 0.0.1a
/// Copyright 2016 Programmers for a Better Tomorrow, Yesterday

part of entities;

/// Cost_Component_Type
/// This is an autogenerated class mapping the MySQL Table Cost_Component_Type to an AvacadORM Entity.

/// List of Cost Components
@Table('Cost_Component_Type')
class Cost_Component_Type extends Entity {
	// ***Table Columns***
	@Column.PrimaryKey('id')
	int id;
	@Column('description')
	String description;

	// ***Table Foreign Key Entities***
	@Column.OneToManyForeignKey('Cost_Component_Type_id')
	List<Cost_Type_Association> cost_type_associations;
}