/// Cost_Organization_Association.dart
/// Version 0.0.1a
/// Copyright 2016 Programmers for a Better Tomorrow, Yesterday

part of entities;

/// Cost_Organization_Association
/// This is an autogenerated class mapping the MySQL Table Cost_Organization_Association to an AvacadORM Entity.

/// If the cost we are estimating is dependent on a particular organization, or we have multiple suppliers, we can create separate Estimated_Product_Cost entities for each of them.
@Table('Cost_Organization_Association')
class Cost_Organization_Association extends Entity {
	// ***Table Columns***
	@Column.PrimaryKey('id')
	int id;
	@Column('Estimated_Product_Cost_id')
	int Estimated_Product_Cost_id;
	@Column('Organization_id')
	int Organization_id;

	// ***Table Foreign Key Entities***
	@Column.ManyToOneForeignKey('Estimated_Product_Cost_id')
	Estimated_Product_Cost estimated_product_cost;
	@Column.ManyToOneForeignKey('Organization_id')
	Organization organization;
}