/// Cost_Type_Association.dart
/// Version 0.0.1a
/// Copyright 2016 Programmers for a Better Tomorrow, Yesterday

part of entities;

/// Cost_Type_Association
/// This is an autogenerated class mapping the MySQL Table Cost_Type_Association to an AvacadORM Entity.

/// Associates a Cost_Component_Type description with an Estimated_Product_Cost enity, to describe in more detail where the cost originates from.
@Table('Cost_Type_Association')
class Cost_Type_Association extends Entity {
	// ***Table Columns***
	@Column.PrimaryKey('id')
	int id;
	@Column('Estimated_Product_Cost_id')
	int Estimated_Product_Cost_id;
	@Column('Cost_Component_Type_id')
	int Cost_Component_Type_id;

	// ***Table Foreign Key Entities***
	@Column.ManyToOneForeignKey('Estimated_Product_Cost_id')
	Estimated_Product_Cost estimated_product_cost;
	@Column.ManyToOneForeignKey('Cost_Component_Type_id')
	Cost_Component_Type cost_component_type;
}