/// Customer_Shipment.dart
/// Version 0.0.1a
/// Copyright 2016 Programmers for a Better Tomorrow, Yesterday

part of entities;

/// Customer_Shipment
/// This is an autogenerated class mapping the MySQL Table Customer_Shipment to an AvacadORM Entity.

/// Subclass of Outgoing_Shipment, representing shipments of goods from the business to the customer.
@Table('Customer_Shipment')
class Customer_Shipment extends Entity {
	// ***Table Columns***
	@Column.PrimaryKey('id')
	int id;
	@Column('Outgoing_Shipment_id')
	int Outgoing_Shipment_id;

	// ***Table Foreign Key Entities***
	@Column.ManyToOneForeignKey('Outgoing_Shipment_id')
	Outgoing_Shipment outgoing_shipment;
}