/// Customer.dart
/// Version 0.0.1a
/// Copyright 2016 Programmers for a Better Tomorrow, Yesterday

part of entities;

/// Customer
/// This is an autogenerated class mapping the MySQL Table Customer to an AvacadORM Entity.

/// Subclass of Party_Role, and applicable irrelevant of the subclass of the given Party entity. This table contains all parties that are active customers.
@Table('Customer')
class Customer extends Entity {
	// ***Table Columns***
	@Column.PrimaryKey('id')
	int id;
	@Column('Party_Role_id')
	int Party_Role_id;

	// ***Table Foreign Key Entities***
	@Column.ManyToOneForeignKey('Party_Role_id')
	Party_Role party_role;
}