/// Drop_Shipment.dart
/// Version 0.0.1a
/// Copyright 2016 Programmers for a Better Tomorrow, Yesterday

part of entities;

/// Drop_Shipment
/// This is an autogenerated class mapping the MySQL Table Drop_Shipment to an AvacadORM Entity.

/// Subclass of Shipment, representing shipments of goods heading to customers, but originating at a third address, never coming to the business first.
@Table('Drop_Shipment')
class Drop_Shipment extends Entity {
	// ***Table Columns***
	@Column.PrimaryKey('id')
	int id;
	@Column('Shipment_id')
	int Shipment_id;

	// ***Table Foreign Key Entities***
	@Column.ManyToOneForeignKey('Shipment_id')
	Shipment shipment;
}