/// Email_Address.dart
/// Version 0.0.1a
/// Copyright 2016 Programmers for a Better Tomorrow, Yesterday

part of entities;

/// Email_Address
/// This is an autogenerated class mapping the MySQL Table Email_Address to an AvacadORM Entity.

/// Subtype of Communication_Mechanism, this is an email address.
@Table('Email_Address')
class Email_Address extends Entity {
	// ***Table Columns***
	@Column.PrimaryKey('id')
	int id;
	@Column('Communication_Mechanism_id')
	int Communication_Mechanism_id;
	@Column('email')
	String email;

	// ***Table Foreign Key Entities***
	@Column.ManyToOneForeignKey('Communication_Mechanism_id')
	Communication_Mechanism communication_mechanism;
}