/// Estimated_Product_Cost.dart
/// Version 0.0.1a
/// Copyright 2016 Programmers for a Better Tomorrow, Yesterday

part of entities;

/// Estimated_Product_Cost
/// This is an autogenerated class mapping the MySQL Table Estimated_Product_Cost to an AvacadORM Entity.

/// Cost of bought goods are often an amalgamation of several pricing structures and surcharges. To support this, we create Estimated_Product_Cost entities for each component of our final price, and sum all the appropriate ones at the time of calculation. This cost is estimated, and should be updated as frequently as necessary.
@Table('Estimated_Product_Cost')
class Estimated_Product_Cost extends Entity {
	// ***Table Columns***
	@Column.PrimaryKey('id')
	int id;
	@Column('from_date')
	DateTime from_date;
	@Column('thru_date')
	DateTime thru_date;
	@Column('cost')
	
	// ***Table Foreign Key Entities***
	@Column.OneToManyForeignKey('Estimated_Product_Cost_id')
	List<Estimated_Materials_Cost> estimated_materials_costs;
	@Column.OneToManyForeignKey('Estimated_Product_Cost_id')
	List<Estimated_Labor_Cost> estimated_labor_costs;
	@Column.OneToManyForeignKey('Estimated_Product_Cost_id')
	List<Estimated_Other_Costs> estimated_other_costss;
	@Column.OneToManyForeignKey('Estimated_Product_Cost_id')
	List<Cost_Product_Association> cost_product_associations;
	@Column.OneToManyForeignKey('Estimated_Product_Cost_id')
	List<Cost_Feature_Association> cost_feature_associations;
	@Column.OneToManyForeignKey('Estimated_Product_Cost_id')
	List<Cost_Type_Association> cost_type_associations;
	@Column.OneToManyForeignKey('Estimated_Product_Cost_id')
	List<Cost_Organization_Association> cost_organization_associations;
}