/// Estimated_Labor_Cost.dart
/// Version 0.0.1a
/// Copyright 2016 Programmers for a Better Tomorrow, Yesterday

part of entities;

/// Estimated_Labor_Cost
/// This is an autogenerated class mapping the MySQL Table Estimated_Labor_Cost to an AvacadORM Entity.

/// Subclass of Estimated_Product_Cost, this represents the cost of the labor invested in a Product.
@Table('Estimated_Labor_Cost')
class Estimated_Labor_Cost extends Entity {
	// ***Table Columns***
	@Column.PrimaryKey('id')
	int id;
	@Column('Estimated_Product_Cost_id')
	int Estimated_Product_Cost_id;

	// ***Table Foreign Key Entities***
	@Column.ManyToOneForeignKey('Estimated_Product_Cost_id')
	Estimated_Product_Cost estimated_product_cost;
}