/// Event_Schedule.dart
/// Version 0.0.1a
/// Copyright 2016 Programmers for a Better Tomorrow, Yesterday

part of entities;

/// Event_Schedule
/// This is an autogenerated class mapping the MySQL Table Event_Schedule to an AvacadORM Entity.

/// All events require a time set aside for them, this table will associate an event with either a reoccuring, or an incidental scheduled time.

/// An event could conceivably recur and also have occasional incidental occurrence.

/// There should only be one Event_Schedule per Event, but as many IS or RS per ES as needed.
@Table('Event_Schedule')
class Event_Schedule extends Entity {
	// ***Table Columns***
	@Column.PrimaryKey('id')
	int id;
	@Column('Event_id')
	int Event_id;

	// ***Table Foreign Key Entities***
	@Column.ManyToOneForeignKey('Event_id')
	Event event;
	@Column.OneToManyForeignKey('Event_Schedule_id')
	List<Incidental_Schedule> incidental_schedules;
	@Column.OneToManyForeignKey('Event_Schedule_id')
	List<Reoccurring_Schedule> reoccurring_schedules;
}
