/// Event_Party_Association_Role.dart
/// Version 0.0.1a
/// Copyright 2016 Programmers for a Better Tomorrow, Yesterday

part of entities;

/// Event_Party_Association_Role
/// This is an autogenerated class mapping the MySQL Table Event_Party_Association_Role to an AvacadORM Entity.

/// Used to tie a role to an Event-Party Relationship. This table allows multiple roles for a single relationship.
@Table('Event_Party_Association_Role')
class Event_Party_Association_Role extends Entity {
	// ***Table Columns***
	@Column.PrimaryKey('id')
	int id;
	@Column('Event_Party_Association_Role_Type_id')
	int Event_Party_Association_Role_Type_id;
	@Column('Event_Party_Association_id')
	int Event_Party_Association_id;

	// ***Table Foreign Key Entities***
	@Column.ManyToOneForeignKey('Event_Party_Association_Role_Type_id')
	Event_Party_Association_Role_Type event_party_association_role_type;
	@Column.ManyToOneForeignKey('Event_Party_Association_id')
	Event_Party_Association event_party_association;
}