/// Event.dart
/// Version 0.0.1a
/// Copyright 2016 Programmers for a Better Tomorrow, Yesterday

part of entities;

/// Event
/// This is an autogenerated class mapping the MySQL Table Event to an AvacadORM Entity.

/// Events are represented by a name, description, and other useful information. This table serves as the base entity that other data will associate with.
@Table('Event')
class Event extends Entity {
	// ***Table Columns***
	@Column.PrimaryKey('id')
	int id;
	@Column('name')
	String name;
	@Column('description')
	String description;

	// ***Table Foreign Key Entities***
	@Column.OneToManyForeignKey('Event_id')
	List<Event_Party_Association> event_party_associations;
	@Column.OneToManyForeignKey('Event_id')
	List<Event_Schedule> event_schedules;
}