/// Facility.dart
/// Version 0.0.1a
/// Copyright 2016 Programmers for a Better Tomorrow, Yesterday

part of entities;

/// Facility
/// This is an autogenerated class mapping the MySQL Table Facility to an AvacadORM Entity.

/// Facility entities represent locations in the world. These facilities can be buildings, departments, or rooms, and may recursively contain other facilities.
@Table('Facility')
class Facility extends Entity {
	// ***Table Columns***
	@Column.PrimaryKey('id')
	int id;
	@Column('name')
	String name;

	// ***Table Foreign Key Entities***
	@Column.OneToManyForeignKey('Facility_id')
	List<Facility_Organization_Association> facility_organization_associations;
	@Column.OneToManyForeignKey('Facility_id')
	List<Facility_Communication_Association> facility_communication_associations;
	@Column.OneToManyForeignKey('Facility_id')
	List<Building> buildings;
	@Column.OneToManyForeignKey('Facility_id')
	List<Room> rooms;
	@Column.OneToManyForeignKey('Facility_id_parent')
	List<Facility_Rollup> facility_parents;
	@Column.OneToManyForeignKey('Facility_id_child')
	List<Facility_Rollup> facility_children;
}
