/// Facility_Communication_Association.dart
/// Version 0.0.1a
/// Copyright 2016 Programmers for a Better Tomorrow, Yesterday

part of entities;

/// Facility_Communication_Association
/// This is an autogenerated class mapping the MySQL Table Facility_Communication_Association to an AvacadORM Entity.

/// This table associates Communication_Mechanisms with Facilities.
@Table('Facility_Communication_Association')
class Facility_Communication_Association extends Entity {
	// ***Table Columns***
	@Column.PrimaryKey('id')
	int id;
	@Column('Facility_id')
	int Facility_id;
	@Column('Communication_Mechanism_id')
	int Communication_Mechanism_id;
	@Column('from_date')
	DateTime from_date;
	@Column('thru_date')
	DateTime thru_date;

	// ***Table Foreign Key Entities***
	@Column.ManyToOneForeignKey('Facility_id')
	Facility facility;
	@Column.ManyToOneForeignKey('Communication_Mechanism_id')
	Communication_Mechanism communication_mechanism;
}