/// Gender_Type.dart
/// Version 0.0.1a
/// Copyright 2016 Programmers for a Better Tomorrow, Yesterday

part of entities;

/// Gender_Type
/// This is an autogenerated class mapping the MySQL Table Gender_Type to an AvacadORM Entity.

/// List of genders currently accepted by the system. This table exists so that genders are expandable as needed.
@Table('Gender_Type')
class Gender_Type extends Entity {
	// ***Table Columns***
	@Column.PrimaryKey('id')
	int id;
	@Column('name')
	String name;
	@Column('description')
	String description;

	// ***Table Foreign Key Entities***
	@Column.OneToManyForeignKey('Gender_Type_id')
	List<Gender_Association> gender_associations;
}