/// Good.dart
/// Version 0.0.1a
/// Copyright 2016 Programmers for a Better Tomorrow, Yesterday

part of entities;

/// Good
/// This is an autogenerated class mapping the MySQL Table Good to an AvacadORM Entity.

/// Subclass of Product representing the delivery of physical goods.
@Table('Good')
class Good extends Entity {
	// ***Table Columns***
	@Column.PrimaryKey('id')
	int id;
	@Column('Product_id')
	int Product_id;

	// ***Table Foreign Key Entities***
	@Column.ManyToOneForeignKey('Product_id')
	Product product;
	@Column.OneToManyForeignKey('Good_id')
	List<Good_Identification> good_identifications;
	@Column.OneToManyForeignKey('Good_id')
	List<Reordering_Guidelines> reordering_guideliness;
	@Column.OneToManyForeignKey('Good_id')
	List<Inventory_Item> inventory_items;
	@Column.OneToManyForeignKey('Good_id')
	List<Shipment_Item> shipment_items;
	@Column.OneToManyForeignKey('Good_id')
	List<Shipment_Receipt> shipment_receipts;
}