/// Good_Identification.dart
/// Version 0.0.1a
/// Copyright 2016 Programmers for a Better Tomorrow, Yesterday

part of entities;

/// Good_Identification
/// This is an autogenerated class mapping the MySQL Table Good_Identification to an AvacadORM Entity.

/// Goods need to be identified, and this table links an arbitrary number of various identification codes to a single good.
@Table('Good_Identification')
class Good_Identification extends Entity {
	// ***Table Columns***
	@Column.PrimaryKey('id')
	int id;
	@Column('Good_id')
	int Good_id;

	// ***Table Foreign Key Entities***
	@Column.ManyToOneForeignKey('Good_id')
	Good good;
	@Column.OneToManyForeignKey('Good_Identification_id')
	List<Manufacturer_ID_Number> manufacturer_id_numbers;
	@Column.OneToManyForeignKey('Good_Identification_id')
	List<SKU> skus;
	@Column.OneToManyForeignKey('Good_Identification_id')
	List<MD_PIN> md_pins;
	@Column.OneToManyForeignKey('Good_Identification_id')
	List<Alternate_Search_String> alternate_search_strings;
}