/// Incidental_Schedule.dart
/// Version 0.0.1a
/// Copyright 2016 Programmers for a Better Tomorrow, Yesterday

part of entities;

/// Incidental_Schedule
/// This is an autogenerated class mapping the MySQL Table Incidental_Schedule to an AvacadORM Entity.

/// If an event will occur on some specific date and time, it should be linked to by this table.
@Table('Incidental_Schedule')
class Incidental_Schedule extends Entity {
	// ***Table Columns***
	@Column.PrimaryKey('id')
	int id;
	@Column('from_datetime')
	DateTime from_datetime;
	@Column('thru_datetime')
	DateTime thru_datetime;
	@Column('Event_Schedule_id')
	int Event_Schedule_id;

	// ***Table Foreign Key Entities***
	@Column.ManyToOneForeignKey('Event_Schedule_id')
	Event_Schedule event_schedule;
}