/// Incoming_Shipment.dart
/// Version 0.0.1a
/// Copyright 2016 Programmers for a Better Tomorrow, Yesterday

part of entities;

/// Incoming_Shipment
/// This is an autogenerated class mapping the MySQL Table Incoming_Shipment to an AvacadORM Entity.

/// Subclass of Shipment, representing shipments of goods traveling to the business.
@Table('Incoming_Shipment')
class Incoming_Shipment extends Entity {
	// ***Table Columns***
	@Column.PrimaryKey('id')
	int id;
	@Column('Shipment_id')
	int Shipment_id;

	// ***Table Foreign Key Entities***
	@Column.ManyToOneForeignKey('Shipment_id')
	Shipment shipment;
	@Column.OneToManyForeignKey('Incoming_Shipment_id')
	List<Purchase_Shipment> purchase_shipments;
	@Column.OneToManyForeignKey('Incoming_Shipment_id')
	List<Customer_Return> customer_returns;
}