/// Informal_Organization.dart
/// Version 0.0.1a
/// Copyright 2016 Programmers for a Better Tomorrow, Yesterday

part of entities;

/// Informal_Organization
/// This is an autogenerated class mapping the MySQL Table Informal_Organization to an AvacadORM Entity.

/// Subtype of organizations, used for informal organizations like clubs, and likely do not have a tax id.
@Table('Informal_Organization')
class Informal_Organization extends Entity {
	// ***Table Columns***
	@Column.PrimaryKey('id')
	int id;
	@Column('Organization_id')
	int Organization_id;

	// ***Table Foreign Key Entities***
	@Column.ManyToOneForeignKey('Organization_id')
	Organization organization;
}