/// Inventory_Variance.dart
/// Version 0.0.1a
/// Copyright 2016 Programmers for a Better Tomorrow, Yesterday

part of entities;

/// Inventory_Variance
/// This is an autogenerated class mapping the MySQL Table Inventory_Variance to an AvacadORM Entity.

/// When counting inventory, if the count comes up wrong we want to track that, and an explanation of why.
@Table('Inventory_Variance')
class Inventory_Variance extends Entity {
	// ***Table Columns***
	@Column.PrimaryKey('id')
	int id;
	@Column('inventory_variance_date')
	DateTime inventory_variance_date;
	@Column('Inventory_Item_id')
	int Inventory_Item_id;
	@Column('Reason_id')
	int Reason_id;
	@Column('quantity')
	int quantity;
	@Column('comment')
	String comment;

	// ***Table Foreign Key Entities***
	@Column.ManyToOneForeignKey('Inventory_Item_id')
	Inventory_Item inventory_item;
	@Column.ManyToOneForeignKey('Reason_id')
	Reason reason;
}