/// Issuance_Reason.dart
/// Version 0.0.1a
/// Copyright 2016 Programmers for a Better Tomorrow, Yesterday

part of entities;

/// Issuance_Reason
/// This is an autogenerated class mapping the MySQL Table Issuance_Reason to an AvacadORM Entity.

/// We often want to tag issuances with an explanation for why we removed this from the inventory, if it is not immediately apparent.
@Table('Issuance_Reason')
class Issuance_Reason extends Entity {
	// ***Table Columns***
	@Column.PrimaryKey('id')
	int id;
	@Column('description')
	String description;

	// ***Table Foreign Key Entities***
	@Column.OneToManyForeignKey('Issuance_Reason_id')
	List<Item_Issuance> item_issuances;
}