/// Item_Issuance_Role_Type.dart
/// Version 0.0.1a
/// Copyright 2016 Programmers for a Better Tomorrow, Yesterday

part of entities;

/// Item_Issuance_Role_Type
/// This is an autogenerated class mapping the MySQL Table Item_Issuance_Role_Type to an AvacadORM Entity.

/// List of Issuance Role Types, to be linked by Item_Issuance_Role.
@Table('Item_Issuance_Role_Type')
class Item_Issuance_Role_Type extends Entity {
	// ***Table Columns***
	@Column.PrimaryKey('id')
	int id;
	@Column('description')
	String description;

	// ***Table Foreign Key Entities***
	@Column.OneToManyForeignKey('Item_Issuance_Role_Type_id')
	List<Item_Issuance_Role> item_issuance_roles;
}