/// Item_Issuance_Role.dart
/// Version 0.0.1a
/// Copyright 2016 Programmers for a Better Tomorrow, Yesterday

part of entities;

/// Item_Issuance_Role
/// This is an autogenerated class mapping the MySQL Table Item_Issuance_Role to an AvacadORM Entity.

/// Different parties serve different roles in relation to the issuance of items. This entity associates an Item_Issuance, a Party, and an Item_Issuance_Role_Type.
@Table('Item_Issuance_Role')
class Item_Issuance_Role extends Entity {
	// ***Table Columns***
	@Column.PrimaryKey('id')
	int id;
	@Column('Party_id')
	int Party_id;
	@Column('Item_Issuance_id')
	int Item_Issuance_id;
	@Column('Item_Issuance_Role_Type_id')
	int Item_Issuance_Role_Type_id;

	// ***Table Foreign Key Entities***
	@Column.ManyToOneForeignKey('Item_Issuance_id')
	Item_Issuance item_issuance;
	@Column.ManyToOneForeignKey('Item_Issuance_Role_Type_id')
	Item_Issuance_Role_Type item_issuance_role_type;
	@Column.ManyToOneForeignKey('Party_id')
	Party party;
}