/// Manufacturer_ID_Number.dart
/// Version 0.0.1a
/// Copyright 2016 Programmers for a Better Tomorrow, Yesterday

part of entities;

/// Manufacturer_ID_Number
/// This is an autogenerated class mapping the MySQL Table Manufacturer_ID_Number to an AvacadORM Entity.

/// List of Manufacturer IDs that should return the linked Good.
@Table('Manufacturer_ID_Number')
class Manufacturer_ID_Number extends Entity {
	// ***Table Columns***
	@Column.PrimaryKey('id')
	int id;
	@Column('Good_Identification_id')
	int Good_Identification_id;
	@Column('manufacturer_id_number')
	String manufacturer_id_number;

	// ***Table Foreign Key Entities***
	@Column.ManyToOneForeignKey('Good_Identification_id')
	Good_Identification good_identification;
}