/// MD_PIN_Child_Reference.dart
/// Version 0.0.1a
/// Copyright 2016 Programmers for a Better Tomorrow, Yesterday

part of entities;

/// MD_PIN_Child_Reference
/// This is an autogenerated class mapping the MySQL Table MD_PIN_Child_Reference to an AvacadORM Entity.

/// When MD-PINs reference children, this association links to the proper child.
@Table('MD_PIN_Child_Reference')
class MD_PIN_Child_Reference extends Entity {
	// ***Table Columns***
	@Column.PrimaryKey('id')
	int id;
	@Column('MD_PIN_id_this')
	int MD_PIN_id_this;
	@Column('md_pin_child_code')
	String md_pin_child_code;
	@Column('MD_PIN_id_child')
	int MD_PIN_id_child;

	// ***Table Foreign Key Entities***
	@Column.ManyToOneForeignKey('MD_PIN_id_this')
	MD_PIN md_pin_this;
	@Column.ManyToOneForeignKey('MD_PIN_id_child')
	MD_PIN md_pin_child;
}
