/// MSRP.dart
/// Version 0.0.1a
/// Copyright 2016 Programmers for a Better Tomorrow, Yesterday

part of entities;

/// MSRP
/// This is an autogenerated class mapping the MySQL Table MSRP to an AvacadORM Entity.

/// Subclass of Price_Component, this represents the Manufacturer's Suggested Retail Price of a Product. This may be useful for informational purposes.
@Table('MSRP')
class MSRP extends Entity {
	// ***Table Columns***
	@Column.PrimaryKey('id')
	int id;
	@Column('Price_Component_id')
	int Price_Component_id;

	// ***Table Foreign Key Entities***
	@Column.ManyToOneForeignKey('Price_Component_id')
	Price_Component price_component;
}