/// Order_Term.dart
/// Version 0.0.1a
/// Copyright 2016 Programmers for a Better Tomorrow, Yesterday

part of entities;

/// Order_Term
/// This is an autogenerated class mapping the MySQL Table Order_Term to an AvacadORM Entity.

/// Defines Terms for orders, accepting either an Order or Order_Item as the target, but not both. The description for the terms exists in Order_Term_Type.
@Table('Order_Term')
class Order_Term extends Entity {
	// ***Table Columns***
	@Column.PrimaryKey('id')
	int id;
	@Column('Order_id')
	int Order_id;
	@Column('Order_Item_id')
	int Order_Item_id;
	@Column('Order_Term_Type_id')
	int Order_Term_Type_id;
	@Column('term_value')
	
	// ***Table Foreign Key Entities***
	@Column.ManyToOneForeignKey('Order_Item_id')
	Order_Item order_item;
	@Column.ManyToOneForeignKey('Order_id')
	Order order;
	@Column.ManyToOneForeignKey('Order_Term_Type_id')
	Order_Term_Type order_term_type;
}