/// Order_Item_Communication_Mechanism.dart
/// Version 0.0.1a
/// Copyright 2016 Programmers for a Better Tomorrow, Yesterday

part of entities;

/// Order_Item_Communication_Mechanism
/// This is an autogenerated class mapping the MySQL Table Order_Item_Communication_Mechanism to an AvacadORM Entity.

/// Communication_Mechanism entities that are related to a specific Order_Item from a larger Order should be added to this list.
@Table('Order_Item_Communication_Mechanism')
class Order_Item_Communication_Mechanism extends Entity {
	// ***Table Columns***
	@Column.PrimaryKey('id')
	int id;
	@Column('Order_Item_id')
	int Order_Item_id;
	@Column('Communication_Mechanism_id')
	int Communication_Mechanism_id;
	@Column('Communication_Mechanism_Purpose_Type_id')
	int Communication_Mechanism_Purpose_Type_id;

	// ***Table Foreign Key Entities***
	@Column.ManyToOneForeignKey('Order_Item_id')
	Order_Item order_item;
	@Column.ManyToOneForeignKey('Communication_Mechanism_id')
	Communication_Mechanism communication_mechanism;
	@Column.ManyToOneForeignKey('Communication_Mechanism_Purpose_Type_id')
	Communication_Mechanism_Purpose_Type communication_mechanism_purpose_type;
}