/// Order_Term_Type.dart
/// Version 0.0.1a
/// Copyright 2016 Programmers for a Better Tomorrow, Yesterday

part of entities;

/// Order_Term_Type
/// This is an autogenerated class mapping the MySQL Table Order_Term_Type to an AvacadORM Entity.

/// List of potential terms to be applied to an Order or Order_Item.
@Table('Order_Term_Type')
class Order_Term_Type extends Entity {
	// ***Table Columns***
	@Column.PrimaryKey('id')
	int id;
	@Column('description')
	String description;

	// ***Table Foreign Key Entities***
	@Column.OneToManyForeignKey('Order_Term_Type_id')
	List<Order_Term> order_terms;
}