/// Order_Item.dart
/// Version 0.0.1a
/// Copyright 2016 Programmers for a Better Tomorrow, Yesterday

part of entities;

/// Order_Item
/// This is an autogenerated class mapping the MySQL Table Order_Item to an AvacadORM Entity.

/// Each item in a given order gets its own reference in this list. Subclasses exist for Order Items depending on whether the order is a Purchase_Order or a Sales_Order. Order_Items can contain other Order_Items recursively, and this is represented by ordered_with_id
@Table('Order_Item')
class Order_Item extends Entity {
	// ***Table Columns***
	@Column.PrimaryKey('id')
	int id;
	@Column('Order_id')
	int Order_id;
	@Column('Product_Feature_id')
	int Product_Feature_id;
	@Column('Product_id')
	int Product_id;
	@Column('ordered_with_id')
	int ordered_with_id;
	@Column('quantity')
	int quantity;
	@Column('unit_price')
		@Column('estimated_delivery_date')
	DateTime estimated_delivery_date;
	@Column('shipping_instructions')
	String shipping_instructions;
	@Column('item_description')
	String item_description;
	@Column('comment')
	String comment;

	// ***Table Foreign Key Entities***
	@Column.ManyToOneForeignKey('Product_Feature_id')
	Product_Feature product_feature;
	@Column.ManyToOneForeignKey('Product_id')
	Product product;
	@Column.ManyToOneForeignKey('ordered_with_id')
	Order_Item order_item;
	@Column.ManyToOneForeignKey('Order_id')
	Order order;
	@Column.OneToManyForeignKey('ordered_with_id')
	List<Order_Item> order_items;
	@Column.OneToManyForeignKey('Order_Item_id')
	List<Purchase_Order_Item> purchase_order_items;
	@Column.OneToManyForeignKey('Order_Item_id')
	List<Sales_Order_Item> sales_order_items;
	@Column.OneToManyForeignKey('Order_Item_id')
	List<Order_Item_Role> order_item_roles;
	@Column.OneToManyForeignKey('Order_Item_id')
	List<Order_Item_Communication_Mechanism> order_item_communication_mechanisms;
	@Column.OneToManyForeignKey('Order_Item_id')
	List<Order_Adjustment> order_adjustments;
	@Column.OneToManyForeignKey('Order_Item_id')
	List<Order_Term> order_terms;
	@Column.OneToManyForeignKey('Order_Item_id')
	List<Order_Status> order_statuss;
	@Column.OneToManyForeignKey('Order_Item_id')
	List<Order_Shipment> order_shipments;
	@Column.OneToManyForeignKey('Order_Item_id')
	List<Shipment_Receipt> shipment_receipts;
}