/// Order_Item_Role_Type.dart
/// Version 0.0.1a
/// Copyright 2016 Programmers for a Better Tomorrow, Yesterday

part of entities;

/// Order_Item_Role_Type
/// This is an autogenerated class mapping the MySQL Table Order_Item_Role_Type to an AvacadORM Entity.

/// List of roles that may be applied to an actor who is party to an Order_Item.
@Table('Order_Item_Role_Type')
class Order_Item_Role_Type extends Entity {
	// ***Table Columns***
	@Column.PrimaryKey('id')
	int id;
	@Column('description')
	String description;

	// ***Table Foreign Key Entities***
	@Column.OneToManyForeignKey('Order_Item_Role_Type_id')
	List<Order_Item_Role> order_item_roles;
}