/// Order_Item_Association.dart
/// Version 0.0.1a
/// Copyright 2016 Programmers for a Better Tomorrow, Yesterday

part of entities;

/// Order_Item_Association
/// This is an autogenerated class mapping the MySQL Table Order_Item_Association to an AvacadORM Entity.

/// When an item on a Purchase Order is being ordered to fill a specific Sales Order, we should associate those items, so we can more easily keep track of them.
@Table('Order_Item_Association')
class Order_Item_Association extends Entity {
	// ***Table Columns***
	@Column.PrimaryKey('id')
	int id;
	@Column.PrimaryKey('Purchase_Order_Item_id')
	int Purchase_Order_Item_id;
	@Column.PrimaryKey('Sales_Order_Item_id')
	int Sales_Order_Item_id;

	// ***Table Foreign Key Entities***
	@Column.ManyToOneForeignKey('Purchase_Order_Item_id')
	Purchase_Order_Item purchase_order_item;
	@Column.ManyToOneForeignKey('Sales_Order_Item_id')
	Sales_Order_Item sales_order_item;
}