/// Order_Adjustment_Type.dart
/// Version 0.0.1a
/// Copyright 2016 Programmers for a Better Tomorrow, Yesterday

part of entities;

/// Order_Adjustment_Type
/// This is an autogenerated class mapping the MySQL Table Order_Adjustment_Type to an AvacadORM Entity.

/// List of reasons for order adjustment.
@Table('Order_Adjustment_Type')
class Order_Adjustment_Type extends Entity {
	// ***Table Columns***
	@Column.PrimaryKey('id')
	int id;
	@Column('description')
	String description;

	// ***Table Foreign Key Entities***
	@Column.OneToManyForeignKey('Order_Adjustment_Type_id')
	List<Order_Adjustment> order_adjustments;
}