/// Order_Shipment.dart
/// Version 0.0.1a
/// Copyright 2016 Programmers for a Better Tomorrow, Yesterday

part of entities;

/// Order_Shipment
/// This is an autogenerated class mapping the MySQL Table Order_Shipment to an AvacadORM Entity.

/// Association between Order_Item entities and their corresponding Shipment_Item entities.
@Table('Order_Shipment')
class Order_Shipment extends Entity {
	// ***Table Columns***
	@Column.PrimaryKey('id')
	int id;
	@Column('Shipment_Item_id')
	int Shipment_Item_id;
	@Column('Order_Item_id')
	int Order_Item_id;
	@Column('quantity')
	int quantity;

	// ***Table Foreign Key Entities***
	@Column.ManyToOneForeignKey('Shipment_Item_id')
	Shipment_Item shipment_item;
	@Column.ManyToOneForeignKey('Order_Item_id')
	Order_Item order_item;
}