/// Order.dart
/// Version 0.0.1a
/// Copyright 2016 Programmers for a Better Tomorrow, Yesterday

part of entities;

/// Order
/// This is an autogenerated class mapping the MySQL Table Order to an AvacadORM Entity.

/// List of all orders in the system, comprising both Purchase_Order entities, and Sales_Order entities. Stores all items associated with the order, the parties and communication mechanisms that are involved in the order, and all roles associated with those parties and communication mechanisms.
@Table('Order')
class Order extends Entity {
	// ***Table Columns***
	@Column.PrimaryKey('id')
	int id;
	@Column('order_date')
	DateTime order_date;
	@Column('entry_date')
	DateTime entry_date;

	// ***Table Foreign Key Entities***
	@Column.OneToManyForeignKey('Order_id')
	List<Sales_Order> sales_orders;
	@Column.OneToManyForeignKey('Order_id')
	List<Purchase_Order> purchase_orders;
	@Column.OneToManyForeignKey('Order_id')
	List<Order_Item> order_items;
	@Column.OneToManyForeignKey('Order_id')
	List<Order_Role> order_roles;
	@Column.OneToManyForeignKey('Order_id')
	List<Order_Communication_Mechanism> order_communication_mechanisms;
	@Column.OneToManyForeignKey('Order_id')
	List<Order_Adjustment> order_adjustments;
	@Column.OneToManyForeignKey('Order_id')
	List<Order_Term> order_terms;
	@Column.OneToManyForeignKey('Order_id')
	List<Order_Status> order_statuss;
}