/// Organization_Role_Classification.dart
/// Version 0.0.1a
/// Copyright 2016 Programmers for a Better Tomorrow, Yesterday

part of entities;

/// Organization_Role_Classification
/// This is an autogenerated class mapping the MySQL Table Organization_Role_Classification to an AvacadORM Entity.

/// Classifies the type of association between a person and an organization, using roles defined in Organization_Role. Indicates what role the person plays in the organization. A single association can have multiple roles.
@Table('Organization_Role_Classification')
class Organization_Role_Classification extends Entity {
	// ***Table Columns***
	@Column.PrimaryKey('id')
	int id;
	@Column('Organization_Person_Association_id')
	int Organization_Person_Association_id;
	@Column('Organization_Role_id')
	int Organization_Role_id;
	@Column('description')
	String description;

	// ***Table Foreign Key Entities***
	@Column.ManyToOneForeignKey('Organization_Role_id')
	Role_in_Organization role_in_organization;
	@Column.ManyToOneForeignKey('Organization_Person_Association_id')
	Organization_Person_Association organization_person_association;
}