/// Organization_Name.dart
/// Version 0.0.1a
/// Copyright 2016 Programmers for a Better Tomorrow, Yesterday

part of entities;

/// Organization_Name
/// This is an autogenerated class mapping the MySQL Table Organization_Name to an AvacadORM Entity.

/// A list of organization names, and the dates those names are relevant. This table allows records for companies that change names during their business with us.
@Table('Organization_Name')
class Organization_Name extends Entity {
	// ***Table Columns***
	@Column.PrimaryKey('id')
	int id;
	@Column('Organization_id')
	int Organization_id;
	@Column('name')
	String name;
	@Column('from_date')
	DateTime from_date;
	@Column('thru_date')
	DateTime thru_date;

	// ***Table Foreign Key Entities***
	@Column.ManyToOneForeignKey('Organization_id')
	Organization organization;
}