/// Organization_Person_Association.dart
/// Version 0.0.1a
/// Copyright 2016 Programmers for a Better Tomorrow, Yesterday

part of entities;

/// Organization_Person_Association
/// This is an autogenerated class mapping the MySQL Table Organization_Person_Association to an AvacadORM Entity.

/// Association of people in organizations. Used to indicate that a given person is in a given organization.
@Table('Organization_Person_Association')
class Organization_Person_Association extends Entity {
	// ***Table Columns***
	@Column.PrimaryKey('id')
	int id;
	@Column('Person_id')
	int Person_id;
	@Column('Organization_id')
	int Organization_id;
	@Column('from_date')
	DateTime from_date;
	@Column('thru_date')
	DateTime thru_date;

	// ***Table Foreign Key Entities***
	@Column.ManyToOneForeignKey('Person_id')
	Person person;
	@Column.ManyToOneForeignKey('Organization_id')
	Organization organization;
	@Column.OneToManyForeignKey('Organization_Person_Association_id')
	List<Organization_Role_Classification> organization_role_classifications;
}