/// Outgoing_Shipment.dart
/// Version 0.0.1a
/// Copyright 2016 Programmers for a Better Tomorrow, Yesterday

part of entities;

/// Outgoing_Shipment
/// This is an autogenerated class mapping the MySQL Table Outgoing_Shipment to an AvacadORM Entity.

/// Subclass of Shipment, representing shipments of goods leaving the business.
@Table('Outgoing_Shipment')
class Outgoing_Shipment extends Entity {
	// ***Table Columns***
	@Column.PrimaryKey('id')
	int id;
	@Column('Shipment_id')
	int Shipment_id;

	// ***Table Foreign Key Entities***
	@Column.ManyToOneForeignKey('Shipment_id')
	Shipment shipment;
	@Column.OneToManyForeignKey('Outgoing_Shipment_id')
	List<Customer_Shipment> customer_shipments;
	@Column.OneToManyForeignKey('Outgoing_Shipment_id')
	List<Purchase_Return> purchase_returns;
}