/// Packaging_Content.dart
/// Version 0.0.1a
/// Copyright 2016 Programmers for a Better Tomorrow, Yesterday

part of entities;

/// Packaging_Content
/// This is an autogenerated class mapping the MySQL Table Packaging_Content to an AvacadORM Entity.

/// Associates Shipment_Packages with Shipment_Items, indicating how many of a particular item from a larger shipment was in a particular package. This allows splitting shipments between packages.
@Table('Packaging_Content')
class Packaging_Content extends Entity {
	// ***Table Columns***
	@Column.PrimaryKey('id')
	int id;
	@Column('Shipment_Package_id')
	int Shipment_Package_id;
	@Column('Shipment_Item_id')
	int Shipment_Item_id;
	@Column('qty')
	int qty;

	// ***Table Foreign Key Entities***
	@Column.ManyToOneForeignKey('Shipment_Package_id')
	Shipment_Package shipment_package;
	@Column.ManyToOneForeignKey('Shipment_Item_id')
	Shipment_Item shipment_item;
}