/// Party_Role.dart
/// Version 0.0.1a
/// Copyright 2016 Programmers for a Better Tomorrow, Yesterday

part of entities;

/// Party_Role
/// This is an autogenerated class mapping the MySQL Table Party_Role to an AvacadORM Entity.

/// Used to classify parties into the roles they play relative to the company. Has several subclasses, and supports multiple concurrent and sequential roles per party.
@Table('Party_Role')
class Party_Role extends Entity {
	// ***Table Columns***
	@Column.PrimaryKey('id')
	int id;
	@Column('Party_id')
	int Party_id;
	@Column('from_date')
	DateTime from_date;
	@Column('thru_date')
	DateTime thru_date;

	// ***Table Foreign Key Entities***
	@Column.ManyToOneForeignKey('Party_id')
	Party party;
	@Column.OneToManyForeignKey('Party_Role_id')
	List<Role_of_Organization> role_of_organizations;
	@Column.OneToManyForeignKey('Party_Role_id')
	List<Person_Role> person_roles;
	@Column.OneToManyForeignKey('Party_Role_id')
	List<Customer> customers;
	@Column.OneToManyForeignKey('Party_Role_id')
	List<Lead> leads;
}