/// Party.dart
/// Version 0.0.1a
/// Copyright 2016 Programmers for a Better Tomorrow, Yesterday

part of entities;

/// Party
/// This is an autogenerated class mapping the MySQL Table Party to an AvacadORM Entity.

/// Core entity representing any person or group we interact with.
@Table('Party')
class Party extends Entity {
	// ***Table Columns***
	@Column.PrimaryKey('id')
	int id;

	// ***Table Foreign Key Entities***
	@Column.OneToManyForeignKey('Party_id')
	List<Party_Description_Association> party_description_associations;
	@Column.OneToManyForeignKey('Party_id')
	List<Party_Role> party_roles;
	@Column.OneToManyForeignKey('Party_id')
	List<Person> persons;
	@Column.OneToManyForeignKey('Party_id')
	List<Organization> organizations;
	@Column.OneToManyForeignKey('Party_id_1')
	List<Party_Relationship> party_relationships_from;
	@Column.OneToManyForeignKey('Party_id_2')
	List<Party_Relationship> party_relationships_to;
	@Column.OneToManyForeignKey('Party_id')
	List<Party_Communication_Association> party_communication_associations;
	@Column.OneToManyForeignKey('Party_id')
	List<Price_Component_Party_Dependency> price_component_party_dependencys;
	@Column.OneToManyForeignKey('Party_id')
	List<Communication_Event_Role> communication_event_roles;
	@Column.OneToManyForeignKey('Party_id')
	List<Order_Item_Role> order_item_roles;
	@Column.OneToManyForeignKey('Party_id')
	List<Order_Role> order_roles;
	@Column.OneToManyForeignKey('Party_id')
	List<Shipment> shipments_from;
	@Column.OneToManyForeignKey('Party_id1')
	List<Shipment> shipments_to;
	@Column.OneToManyForeignKey('Party_id')
	List<Shipment_Receipt_Role> shipment_receipt_roles;
	@Column.OneToManyForeignKey('Party_id')
	List<Item_Issuance_Role> item_issuance_roles;
	@Column.OneToManyForeignKey('Party_id')
	List<Event_Party_Association> event_party_associations;
}
