/// Party_Description.dart
/// Version 0.0.1a
/// Copyright 2016 Programmers for a Better Tomorrow, Yesterday

part of entities;

/// Party_Description
/// This is an autogenerated class mapping the MySQL Table Party_Description to an AvacadORM Entity.

/// List of party descriptions. These description will be linked to a party by a row in Party_Description_Association.
/// Parties may have an arbitrary number of descriptions, and vice versa.
@Table('Party_Description')
class Party_Description extends Entity {
	// ***Table Columns***
	@Column.PrimaryKey('id')
	int id;
	@Column('description')
	String description;

	// ***Table Foreign Key Entities***
	@Column.OneToManyForeignKey('Party_Description_id')
	List<Party_Description_Association> party_description_associations;
}
