/// Party_Relationship.dart
/// Version 0.0.1a
/// Copyright 2016 Programmers for a Better Tomorrow, Yesterday

part of entities;

/// Party_Relationship
/// This is an autogenerated class mapping the MySQL Table Party_Relationship to an AvacadORM Entity.

/// A relationship between two parties, as well as the dates that relationship is active, and a description of the relationship.
@Table('Party_Relationship')
class Party_Relationship extends Entity {
	// ***Table Columns***
	@Column.PrimaryKey('id')
	int id;
	@Column('Party_id_1')
	int Party_id_1;
	@Column('Party_id_2')
	int Party_id_2;
	@Column('from_date')
	DateTime from_date;
	@Column('thru_date')
	DateTime thru_date;
	@Column('comment')
	String comment;

	// ***Table Foreign Key Entities***
	@Column.ManyToOneForeignKey('Party_id_1')
	Party party_1;
	@Column.ManyToOneForeignKey('Party_id_2')
	Party party_2;
	@Column.OneToManyForeignKey('Party_Relationship_id')
	List<Relationship_Note> relationship_notes;
	@Column.OneToManyForeignKey('Party_Relationship_id')
	List<Communication_Event> communication_events;
}
