/// Party_Communication_Association.dart
/// Version 0.0.1a
/// Copyright 2016 Programmers for a Better Tomorrow, Yesterday

part of entities;

/// Party_Communication_Association
/// This is an autogenerated class mapping the MySQL Table Party_Communication_Association to an AvacadORM Entity.

/// Associates a Communication_Mechanism with a Party, for the purposes of having contact info tied to parties in our system.
@Table('Party_Communication_Association')
class Party_Communication_Association extends Entity {
	// ***Table Columns***
	@Column.PrimaryKey('id')
	int id;
	@Column('Communication_Mechanism_id')
	int Communication_Mechanism_id;
	@Column('Party_id')
	int Party_id;
	@Column('from_date')
	DateTime from_date;
	@Column('thru_date')
	DateTime thru_date;
	@Column('note')
	String note;

	// ***Table Foreign Key Entities***
	@Column.ManyToOneForeignKey('Communication_Mechanism_id')
	Communication_Mechanism communication_mechanism;
	@Column.ManyToOneForeignKey('Party_id')
	Party party;
}