/// Party_Description_Association.dart
/// Version 0.0.1a
/// Copyright 2016 Programmers for a Better Tomorrow, Yesterday

part of entities;

/// Party_Description_Association
/// This is an autogenerated class mapping the MySQL Table Party_Description_Association to an AvacadORM Entity.

/// Associates Party entities with Party_Description entities.
@Table('Party_Description_Association')
class Party_Description_Association extends Entity {
	// ***Table Columns***
	@Column.PrimaryKey('id')
	int id;
	@Column('Party_Description_id')
	int Party_Description_id;
	@Column('Party_id')
	int Party_id;
	@Column('from_date')
	DateTime from_date;
	@Column('thru_date')
	DateTime thru_date;

	// ***Table Foreign Key Entities***
	@Column.ManyToOneForeignKey('Party_Description_id')
	Party_Description party_description;
	@Column.ManyToOneForeignKey('Party_id')
	Party party;
}