/// Person_Role.dart
/// Version 0.0.1a
/// Copyright 2016 Programmers for a Better Tomorrow, Yesterday

part of entities;

/// Person_Role
/// This is an autogenerated class mapping the MySQL Table Person_Role to an AvacadORM Entity.

/// Subclass of Party_Role that supports all Person entity relevant roles.
@Table('Person_Role')
class Person_Role extends Entity {
	// ***Table Columns***
	@Column.PrimaryKey('id')
	int id;
	@Column('Party_Role_id')
	int Party_Role_id;

	// ***Table Foreign Key Entities***
	@Column.ManyToOneForeignKey('Party_Role_id')
	Party_Role party_role;
	@Column.OneToManyForeignKey('Person_Role_id')
	List<Employee> employees;
	@Column.OneToManyForeignKey('Person_Role_id')
	List<Contractor> contractors;
	@Column.OneToManyForeignKey('Person_Role_id')
	List<Contact> contacts;
}