/// Picklist.dart
/// Version 0.0.1a
/// Copyright 2016 Programmers for a Better Tomorrow, Yesterday

part of entities;

/// Picklist
/// This is an autogenerated class mapping the MySQL Table Picklist to an AvacadORM Entity.

/// This is the list of items to collect and remove from inventory.
@Table('Picklist')
class Picklist extends Entity {
	// ***Table Columns***
	@Column.PrimaryKey('id')
	int id;
	@Column('date_created')
	DateTime date_created;

	// ***Table Foreign Key Entities***
	@Column.OneToManyForeignKey('Picklist_id')
	List<Picklist_Item> picklist_items;
}