/// Picklist_Item.dart
/// Version 0.0.1a
/// Copyright 2016 Programmers for a Better Tomorrow, Yesterday

part of entities;

/// Picklist_Item
/// This is an autogenerated class mapping the MySQL Table Picklist_Item to an AvacadORM Entity.

/// If items in an issuance need to be collected, they can be added to a Picklist, as a temporary list of items to seek out in the field.
@Table('Picklist_Item')
class Picklist_Item extends Entity {
	// ***Table Columns***
	@Column.PrimaryKey('id')
	int id;
	@Column('quantity')
	int quantity;
	@Column('Picklist_id')
	int Picklist_id;
	@Column('Inventory_Item_id')
	int Inventory_Item_id;

	// ***Table Foreign Key Entities***
	@Column.ManyToOneForeignKey('Picklist_id')
	Picklist picklist;
	@Column.ManyToOneForeignKey('Inventory_Item_id')
	Inventory_Item inventory_item;
	@Column.OneToManyForeignKey('Picklist_Item_id')
	List<Item_Issuance> item_issuances;
}