/// Price_Order_Value_Dependency.dart
/// Version 0.0.1a
/// Copyright 2016 Programmers for a Better Tomorrow, Yesterday

part of entities;

/// Price_Order_Value_Dependency
/// This is an autogenerated class mapping the MySQL Table Price_Order_Value_Dependency to an AvacadORM Entity.

/// Entries in this table restrict a Price_Component to applying only to a particular range of order values.
@Table('Price_Order_Value_Dependency')
class Price_Order_Value_Dependency extends Entity {
	// ***Table Columns***
	@Column.PrimaryKey('id')
	int id;
	@Column('Price_Component_id')
	int Price_Component_id;
	@Column('Order_Value_id')
	int Order_Value_id;

	// ***Table Foreign Key Entities***
	@Column.ManyToOneForeignKey('Price_Component_id')
	Price_Component price_component;
	@Column.ManyToOneForeignKey('Order_Value_id')
	Order_Value order_value;
}