/// Price_Component_Product_Category_Dependency.dart
/// Version 0.0.1a
/// Copyright 2016 Programmers for a Better Tomorrow, Yesterday

part of entities;

/// Price_Component_Product_Category_Dependency
/// This is an autogenerated class mapping the MySQL Table Price_Component_Product_Category_Dependency to an AvacadORM Entity.

/// Entries in this table restrict a Price_Component to applying only to a particular Product_Category.
@Table('Price_Component_Product_Category_Dependency')
class Price_Component_Product_Category_Dependency extends Entity {
	// ***Table Columns***
	@Column.PrimaryKey('id')
	int id;
	@Column('Price_Component_id')
	int Price_Component_id;
	@Column('Product_Category_id')
	int Product_Category_id;

	// ***Table Foreign Key Entities***
	@Column.ManyToOneForeignKey('Price_Component_id')
	Price_Component price_component;
	@Column.ManyToOneForeignKey('Product_Category_id')
	Product_Category product_category;
}