/// Price_Sale_Type_Dependency.dart
/// Version 0.0.1a
/// Copyright 2016 Programmers for a Better Tomorrow, Yesterday

part of entities;

/// Price_Sale_Type_Dependency
/// This is an autogenerated class mapping the MySQL Table Price_Sale_Type_Dependency to an AvacadORM Entity.

/// Entries in this table restrict a Price_Component to applying only to a particular Sale_Type.
@Table('Price_Sale_Type_Dependency')
class Price_Sale_Type_Dependency extends Entity {
	// ***Table Columns***
	@Column.PrimaryKey('id')
	int id;
	@Column('Price_Component_id')
	int Price_Component_id;
	@Column('Sale_Type_id')
	int Sale_Type_id;

	// ***Table Foreign Key Entities***
	@Column.ManyToOneForeignKey('Price_Component_id')
	Price_Component price_component;
	@Column.ManyToOneForeignKey('Sale_Type_id')
	Sale_Type sale_type;
}