/// Price_Component_Product_Association.dart
/// Version 0.0.1a
/// Copyright 2016 Programmers for a Better Tomorrow, Yesterday

part of entities;

/// Price_Component_Product_Association
/// This is an autogenerated class mapping the MySQL Table Price_Component_Product_Association to an AvacadORM Entity.

/// Associates a Price_Component with a Product.
@Table('Price_Component_Product_Association')
class Price_Component_Product_Association extends Entity {
	// ***Table Columns***
	@Column.PrimaryKey('id')
	int id;
	@Column('Price_Component_id')
	int Price_Component_id;
	@Column('Product_id')
	int Product_id;

	// ***Table Foreign Key Entities***
	@Column.ManyToOneForeignKey('Price_Component_id')
	Price_Component price_component;
	@Column.ManyToOneForeignKey('Product_id')
	Product product;
}