/// Product_Category.dart
/// Version 0.0.1a
/// Copyright 2016 Programmers for a Better Tomorrow, Yesterday

part of entities;

/// Product_Category
/// This is an autogenerated class mapping the MySQL Table Product_Category to an AvacadORM Entity.

/// List of Product_Category entities that may be associated with Product entities.
@Table('Product_Category')
class Product_Category extends Entity {
	// ***Table Columns***
	@Column.PrimaryKey('id')
	int id;
	@Column('description')
	String description;

	// ***Table Foreign Key Entities***
	@Column.OneToManyForeignKey('Product_Category_id')
	List<Product_Category_Classification> product_category_classifications;
	@Column.OneToManyForeignKey('Product_Category_id_parent')
	List<Product_Category_Rollup> product_category_parents;
	@Column.OneToManyForeignKey('Product_Category_id_child')
	List<Product_Category_Rollup> product_category_children;
	@Column.OneToManyForeignKey('Product_Category_id')
	List<Price_Component_Product_Category_Dependency> price_component_product_category_dependencys;
	@Column.OneToManyForeignKey('Product_Category_id')
	List<Sales_Tax_Lookup> sales_tax_lookups;
}
