/// Product.dart
/// Version 0.0.1a
/// Copyright 2016 Programmers for a Better Tomorrow, Yesterday

part of entities;

/// Product
/// This is an autogenerated class mapping the MySQL Table Product to an AvacadORM Entity.

/// Core entity representing any Product we purchase, sell, and/or use.
@Table('Product')
class Product extends Entity {
	// ***Table Columns***
	@Column.PrimaryKey('id')
	int id;
	@Column('name')
	String name;
	@Column('introduction_date')
	DateTime introduction_date;
	@Column('discontinuation_date')
	DateTime discontinuation_date;
	@Column('eol_date')
	DateTime eol_date;
	@Column('comment')
	String comment;

	// ***Table Foreign Key Entities***
	@Column.OneToManyForeignKey('Product_id')
	List<Good> goods;
	@Column.OneToManyForeignKey('Product_id')
	List<Service> services;
	@Column.OneToManyForeignKey('Product_id')
	List<Product_Category_Classification> product_category_classifications;
	@Column.OneToManyForeignKey('Product_id')
	List<Product_Feature_Applicability> product_feature_applicabilitys;
	@Column.OneToManyForeignKey('Product_id')
	List<Supplier_Product> supplier_products;
	@Column.OneToManyForeignKey('Product_id')
	List<Price_Component_Product_Association> price_component_product_associations;
	@Column.OneToManyForeignKey('Product_id')
	List<Cost_Product_Association> cost_product_associations;
	@Column.OneToManyForeignKey('Product_id_parent')
	List<Product_Component> product_components;
	@Column.OneToManyForeignKey('Product_id_child')
	List<Product_Component> child_products;
	@Column.OneToManyForeignKey('Product_id_original')
	List<Product_Substitute> product_substitute_original;
	@Column.OneToManyForeignKey('Product_id_substitute')
	List<Product_Substitute> product_substitute;
	@Column.OneToManyForeignKey('Product_id_original')
	List<Product_Obsolescense> product_obsolescense_original;
	@Column.OneToManyForeignKey('Product_id_replacement')
	List<Product_Obsolescense> product_obsolescense_replacement;
	@Column.OneToManyForeignKey('Product_id_a')
	List<Product_Complement> product_complements;
	@Column.OneToManyForeignKey('Product_id_b')
	List<Product_Complement> product_complemented;
	@Column.OneToManyForeignKey('Product_id_a')
	List<Product_Incompatibility> product_incompatibilitys_a;
	@Column.OneToManyForeignKey('Product_id_b')
	List<Product_Incompatibility> product_incompatibilitys_b;
	@Column.OneToManyForeignKey('Product_id')
	List<Order_Item> order_items;
}
