/// Product_Feature.dart
/// Version 0.0.1a
/// Copyright 2016 Programmers for a Better Tomorrow, Yesterday

part of entities;

/// Product_Feature
/// This is an autogenerated class mapping the MySQL Table Product_Feature to an AvacadORM Entity.

/// Core entity representing any Product_Feature relevant to a Product.
@Table('Product_Feature')
class Product_Feature extends Entity {
	// ***Table Columns***
	@Column.PrimaryKey('id')
	int id;
	@Column('description')
	String description;

	// ***Table Foreign Key Entities***
	@Column.OneToManyForeignKey('Product_Feature_id')
	List<Product_Feature_Applicability> product_feature_applicabilitys;
	@Column.OneToManyForeignKey('Product_Feature_id')
	List<Price_Component_Feature_Association> price_component_feature_associations;
	@Column.OneToManyForeignKey('Product_Feature_id')
	List<Cost_Feature_Association> cost_feature_associations;
	@Column.OneToManyForeignKey('Product_Feature_id')
	List<Order_Item> order_items;
	@Column.OneToManyForeignKey('Product_Feature_id')
	List<Shipment_Item_Feature> shipment_item_features;
}