/// Product_Feature_Applicability.dart
/// Version 0.0.1a
/// Copyright 2016 Programmers for a Better Tomorrow, Yesterday

part of entities;

/// Product_Feature_Applicability
/// This is an autogenerated class mapping the MySQL Table Product_Feature_Applicability to an AvacadORM Entity.

/// Associates a Product with a Product_Feature, and designates the applicability of that feature.
@Table('Product_Feature_Applicability')
class Product_Feature_Applicability extends Entity {
	// ***Table Columns***
	@Column.PrimaryKey('id')
	int id;
	@Column('Product_id')
	int Product_id;
	@Column('Product_Feature_id')
	int Product_Feature_id;
	@Column('from_date')
	DateTime from_date;
	@Column('thru_date')
	DateTime thru_date;

	// ***Table Foreign Key Entities***
	@Column.ManyToOneForeignKey('Product_id')
	Product product;
	@Column.ManyToOneForeignKey('Product_Feature_id')
	Product_Feature product_feature;
	@Column.OneToManyForeignKey('Product_Feature_Applicability_id')
	List<Required_Feature> required_features;
	@Column.OneToManyForeignKey('Product_Feature_Applicability_id')
	List<Optional_Feature> optional_features;
	@Column.OneToManyForeignKey('Product_Feature_Applicability_id')
	List<Standard_Feature> standard_features;
	@Column.OneToManyForeignKey('Product_Feature_Applicability_id')
	List<Selectable_Feature> selectable_features;
}