/// Product_Substitute.dart
/// Version 0.0.1a
/// Copyright 2016 Programmers for a Better Tomorrow, Yesterday

part of entities;

/// Product_Substitute
/// This is an autogenerated class mapping the MySQL Table Product_Substitute to an AvacadORM Entity.

/// When one Product is a reasonable substitute for another Product, it is helpful to record that information. This table stores those relationships, as well as how many objects the substitute can replace, and the date range this relationship is valid through. (Quantity can be relevant, example: 1 box of 12 pencils can substitute for 12 pencils)
@Table('Product_Substitute')
class Product_Substitute extends Entity {
	// ***Table Columns***
	@Column.PrimaryKey('id')
	int id;
	@Column('from_date')
	DateTime from_date;
	@Column('thru_date')
	DateTime thru_date;
	@Column('quantity')
	int quantity;
	@Column('comment')
	String comment;
	@Column('Product_id_original')
	int Product_id_original;
	@Column('Product_id_substitute')
	int Product_id_substitute;

	// ***Table Foreign Key Entities***
	@Column.ManyToOneForeignKey('Product_id_original')
	Product product_original;
	@Column.ManyToOneForeignKey('Product_id_substitute')
	Product product_substitute;
}
