/// Product_Obsolescense.dart
/// Version 0.0.1a
/// Copyright 2016 Programmers for a Better Tomorrow, Yesterday

part of entities;

/// Product_Obsolescense
/// This is an autogenerated class mapping the MySQL Table Product_Obsolescense to an AvacadORM Entity.

/// When one Product is being discontinued, and superceded by another Product, it is helpful to record that information. This table stores those relationships, as well as the reason for the depreciation, and the date of obscelescence.
@Table('Product_Obsolescense')
class Product_Obsolescense extends Entity {
	// ***Table Columns***
	@Column.PrimaryKey('id')
	int id;
	@Column('supercession_date')
	DateTime supercession_date;
	@Column('reason')
	String reason;
	@Column('Product_id_original')
	int Product_id_original;
	@Column('Product_id_replacement')
	int Product_id_replacement;

	// ***Table Foreign Key Entities***
	@Column.ManyToOneForeignKey('Product_id_original')
	Product product_original;
	@Column.ManyToOneForeignKey('Product_id_replacement')
	Product product_replacement;
}
