/// Product_Incompatibility.dart
/// Version 0.0.1a
/// Copyright 2016 Programmers for a Better Tomorrow, Yesterday

part of entities;

/// Product_Incompatibility
/// This is an autogenerated class mapping the MySQL Table Product_Incompatibility to an AvacadORM Entity.

/// When one Product is incompatible with another Product, it is helpful to record that information. This table stores those relationships, as well as the reason for the incompatibility, and the date range the relationship is valid through.
@Table('Product_Incompatibility')
class Product_Incompatibility extends Entity {
	// ***Table Columns***
	@Column.PrimaryKey('id')
	int id;
	@Column('from_date')
	DateTime from_date;
	@Column('thru_date')
	DateTime thru_date;
	@Column('reason')
	String reason;
	@Column('Product_id_a')
	int Product_id_a;
	@Column('Product_id_b')
	int Product_id_b;

	// ***Table Foreign Key Entities***
	@Column.ManyToOneForeignKey('Product_id_a')
	Product product_a;
	@Column.ManyToOneForeignKey('Product_id_b')
	Product product_b;
}
