/// Purchase_Return.dart
/// Version 0.0.1a
/// Copyright 2016 Programmers for a Better Tomorrow, Yesterday

part of entities;

/// Purchase_Return
/// This is an autogenerated class mapping the MySQL Table Purchase_Return to an AvacadORM Entity.

/// Subclass of Outgoing_Shipment, representing shipments returning goods purchased to suppliers.
@Table('Purchase_Return')
class Purchase_Return extends Entity {
	// ***Table Columns***
	@Column.PrimaryKey('id')
	int id;
	@Column('Outgoing_Shipment_id')
	int Outgoing_Shipment_id;

	// ***Table Foreign Key Entities***
	@Column.ManyToOneForeignKey('Outgoing_Shipment_id')
	Outgoing_Shipment outgoing_shipment;
}