/// Reason.dart
/// Version 0.0.1a
/// Copyright 2016 Programmers for a Better Tomorrow, Yesterday

part of entities;

/// Reason
/// This is an autogenerated class mapping the MySQL Table Reason to an AvacadORM Entity.

/// List of reasons given for inventory variances.
@Table('Reason')
class Reason extends Entity {
	// ***Table Columns***
	@Column.PrimaryKey('id')
	int id;
	@Column('description')
	String description;

	// ***Table Foreign Key Entities***
	@Column.OneToManyForeignKey('Reason_id')
	List<Inventory_Variance> inventory_variances;
}