/// Relationship_Note.dart
/// Version 0.0.1a
/// Copyright 2016 Programmers for a Better Tomorrow, Yesterday

part of entities;

/// Relationship_Note
/// This is an autogenerated class mapping the MySQL Table Relationship_Note to an AvacadORM Entity.

/// Timestamped notes relating to a given Party_Relationship. These would be for logging information relevant to the relationship.
@Table('Relationship_Note')
class Relationship_Note extends Entity {
	// ***Table Columns***
	@Column.PrimaryKey('id')
	int id;
	@Column('Party_Relationship_id')
	int Party_Relationship_id;
	@Column('timestamp')
	DateTime timestamp;
	@Column('note')
	String note;

	// ***Table Foreign Key Entities***
	@Column.ManyToOneForeignKey('Party_Relationship_id')
	Party_Relationship party_relationship;
}