/// Reordering_Guidelines.dart
/// Version 0.0.1a
/// Copyright 2016 Programmers for a Better Tomorrow, Yesterday

part of entities;

/// Reordering_Guidelines
/// This is an autogenerated class mapping the MySQL Table Reordering_Guidelines to an AvacadORM Entity.

/// Helper list, so we can store info on how many of a good to keep on hand, and how to reorder effectively.
@Table('Reordering_Guidelines')
class Reordering_Guidelines extends Entity {
	// ***Table Columns***
	@Column.PrimaryKey('id')
	int id;
	@Column('Good_id')
	int Good_id;
	@Column('from_date')
	DateTime from_date;
	@Column('thru_date')
	DateTime thru_date;
	@Column('reorder_quantity')
	int reorder_quantity;
	@Column('reorder_level')
	int reorder_level;

	// ***Table Foreign Key Entities***
	@Column.ManyToOneForeignKey('Good_id')
	Good good;
}