/// Role_of_Organization.dart
/// Version 0.0.1a
/// Copyright 2016 Programmers for a Better Tomorrow, Yesterday

part of entities;

/// Role_of_Organization
/// This is an autogenerated class mapping the MySQL Table Role_of_Organization to an AvacadORM Entity.

/// Subclass of Party_Role that supports all Person entity relevant roles.
@Table('Role_of_Organization')
class Role_of_Organization extends Entity {
	// ***Table Columns***
	@Column.PrimaryKey('id')
	int id;
	@Column('Party_Role_id')
	int Party_Role_id;

	// ***Table Foreign Key Entities***
	@Column.ManyToOneForeignKey('Party_Role_id')
	Party_Role party_role;
	@Column.OneToManyForeignKey('Organization_Role_id')
	List<Distributor> distributors;
	@Column.OneToManyForeignKey('Organization_Role_id')
	List<Internal_Department> internal_departments;
	@Column.OneToManyForeignKey('Organization_Role_id')
	List<Competition> competitions;
}