/// Role_in_Organization.dart
/// Version 0.0.1a
/// Copyright 2016 Programmers for a Better Tomorrow, Yesterday

part of entities;

/// Role_in_Organization
/// This is an autogenerated class mapping the MySQL Table Role_in_Organization to an AvacadORM Entity.

/// List of roles that exist within organizations. 
@Table('Role_in_Organization')
class Role_in_Organization extends Entity {
	// ***Table Columns***
	@Column.PrimaryKey('id')
	int id;
	@Column('name')
	String name;

	// ***Table Foreign Key Entities***
	@Column.OneToManyForeignKey('Organization_Role_id')
	List<Organization_Role_Classification> organization_role_classifications;
}