/// Room.dart
/// Version 0.0.1a
/// Copyright 2016 Programmers for a Better Tomorrow, Yesterday

part of entities;

/// Room
/// This is an autogenerated class mapping the MySQL Table Room to an AvacadORM Entity.

/// Rooms are a subtype of facilities, representing physical rooms, generally within buildings, though they don't need to be.
@Table('Room')
class Room extends Entity {
	// ***Table Columns***
	@Column.PrimaryKey('id')
	int id;
	@Column('Facility_id')
	int Facility_id;

	// ***Table Foreign Key Entities***
	@Column.ManyToOneForeignKey('Facility_id')
	Facility facility;
}