/// Sales_Tax_State_Dependency.dart
/// Version 0.0.1a
/// Copyright 2016 Programmers for a Better Tomorrow, Yesterday

part of entities;

/// Sales_Tax_State_Dependency
/// This is an autogenerated class mapping the MySQL Table Sales_Tax_State_Dependency to an AvacadORM Entity.

/// 
@Table('Sales_Tax_State_Dependency')
class Sales_Tax_State_Dependency extends Entity {
	// ***Table Columns***
	@Column.PrimaryKey('id')
	int id;
	@Column('state_code')
	String state_code;
	@Column('Sales_Tax_Lookup_id')
	int Sales_Tax_Lookup_id;

	// ***Table Foreign Key Entities***
	@Column.ManyToOneForeignKey('Sales_Tax_Lookup_id')
	Sales_Tax_Lookup sales_tax_lookup;
}