/// Sales_Order.dart
/// Version 0.0.1a
/// Copyright 2016 Programmers for a Better Tomorrow, Yesterday

part of entities;

/// Sales_Order
/// This is an autogenerated class mapping the MySQL Table Sales_Order to an AvacadORM Entity.

/// Subclass of Order representing Sales Orders, selling Products to Customers.
@Table('Sales_Order')
class Sales_Order extends Entity {
	// ***Table Columns***
	@Column.PrimaryKey('id')
	int id;
	@Column('Order_id')
	int Order_id;

	// ***Table Foreign Key Entities***
	@Column.ManyToOneForeignKey('Order_id')
	Order order;
}