/// Selectable_Feature.dart
/// Version 0.0.1a
/// Copyright 2016 Programmers for a Better Tomorrow, Yesterday

part of entities;

/// Selectable_Feature
/// This is an autogenerated class mapping the MySQL Table Selectable_Feature to an AvacadORM Entity.

/// Subclass of Product_Feature_Applicability, this indicates the associated Product_Feature is a selectable feature on the associated Product. An option must be selected for these features, but there may be several options to choose between.
@Table('Selectable_Feature')
class Selectable_Feature extends Entity {
	// ***Table Columns***
	@Column.PrimaryKey('id')
	int id;
	@Column('Product_Feature_Applicability_id')
	int Product_Feature_Applicability_id;
	@Column('Selectable_Feature_Group_id')
	int Selectable_Feature_Group_id;

	// ***Table Foreign Key Entities***
	@Column.ManyToOneForeignKey('Product_Feature_Applicability_id')
	Product_Feature_Applicability product_feature_applicability;
	@Column.ManyToOneForeignKey('Selectable_Feature_Group_id')
	Selectable_Feature_Group selectable_feature_group;
}