/// Service.dart
/// Version 0.0.1a
/// Copyright 2016 Programmers for a Better Tomorrow, Yesterday

part of entities;

/// Service
/// This is an autogenerated class mapping the MySQL Table Service to an AvacadORM Entity.

/// Subclass of Product representing the delivery of services and/or expertise.
@Table('Service')
class Service extends Entity {
	// ***Table Columns***
	@Column.PrimaryKey('id')
	int id;
	@Column('Product_id')
	int Product_id;

	// ***Table Foreign Key Entities***
	@Column.ManyToOneForeignKey('Product_id')
	Product product;
}