/// Shipment_Status.dart
/// Version 0.0.1a
/// Copyright 2016 Programmers for a Better Tomorrow, Yesterday

part of entities;

/// Shipment_Status
/// This is an autogenerated class mapping the MySQL Table Shipment_Status to an AvacadORM Entity.

/// Used to track changes to status of a shipment, with a timestamp and a link to a description of the new status type.
@Table('Shipment_Status')
class Shipment_Status extends Entity {
	// ***Table Columns***
	@Column.PrimaryKey('id')
	int id;
	@Column('Shipment_id')
	int Shipment_id;
	@Column('Shipment_Status_Type_id')
	int Shipment_Status_Type_id;
	@Column('status_timestamp')
	DateTime status_timestamp;

	// ***Table Foreign Key Entities***
	@Column.ManyToOneForeignKey('Shipment_id')
	Shipment shipment;
	@Column.ManyToOneForeignKey('Shipment_Status_Type_id')
	Shipment_Status_Type shipment_status_type;
}