/// Shipment_Receipt.dart
/// Version 0.0.1a
/// Copyright 2016 Programmers for a Better Tomorrow, Yesterday

part of entities;

/// Shipment_Receipt
/// This is an autogenerated class mapping the MySQL Table Shipment_Receipt to an AvacadORM Entity.

/// When receiving an item from a shipment, we store the information on what is received in a Shipment_Receipt entity. This has an optional link to a Good_id, if we are receiving an existing product. It also has an optional link to an Order_Item, if the received product was ordered, we can track the progress from order to receipt. It has a mandatory link to an Inventory_Item entity, for putting the object into stock.
@Table('Shipment_Receipt')
class Shipment_Receipt extends Entity {
	// ***Table Columns***
	@Column.PrimaryKey('id')
	int id;
	@Column('Shipment_Package_id')
	int Shipment_Package_id;
	@Column('Good_id')
	int Good_id;
	@Column('Order_Item_id')
	int Order_Item_id;
	@Column('Inventory_Item_id')
	int Inventory_Item_id;
	@Column('Rejection_Reason_id')
	int Rejection_Reason_id;
	@Column('datetime_received')
	DateTime datetime_received;
	@Column('item_description')
	String item_description;
	@Column('quantity_accepted')
	int quantity_accepted;
	@Column('quantity_rejected')
	int quantity_rejected;

	// ***Table Foreign Key Entities***
	@Column.ManyToOneForeignKey('Rejection_Reason_id')
	Rejection_Reason rejection_reason;
	@Column.ManyToOneForeignKey('Shipment_Package_id')
	Shipment_Package shipment_package;
	@Column.ManyToOneForeignKey('Good_id')
	Good good;
	@Column.ManyToOneForeignKey('Inventory_Item_id')
	Inventory_Item inventory_item;
	@Column.ManyToOneForeignKey('Order_Item_id')
	Order_Item order_item;
	@Column.OneToManyForeignKey('Shipment_Receipt_id')
	List<Shipment_Receipt_Role> shipment_receipt_roles;
}