/// Shipment.dart
/// Version 0.0.1a
/// Copyright 2016 Programmers for a Better Tomorrow, Yesterday

part of entities;

/// Shipment
/// This is an autogenerated class mapping the MySQL Table Shipment to an AvacadORM Entity.

/// Base class for tracking known information about shipments of goods in or out of the business. Has several sub-classes, and links to a handful of other entities.

/// Party_id - Shipped From
/// Party_id1 - Shipped To
/// Address_id - Shipped From
/// Address_id1 - Shipped To
/// Phone_Number_id - Contact phone number
@Table('Shipment')
class Shipment extends Entity {
	// ***Table Columns***
	@Column.PrimaryKey('id')
	int id;
	@Column('Party_id')
	int Party_id;
	@Column('Party_id1')
	int Party_id1;
	@Column('Address_id')
	int Address_id;
	@Column('Address_id1')
	int Address_id1;
	@Column('Phone_Number_id')
	int Phone_Number_id;
	@Column('estimated_ship_date')
	DateTime estimated_ship_date;
	@Column('estimated_ready_date')
	DateTime estimated_ready_date;
	@Column('estimated_arrival_date')
	DateTime estimated_arrival_date;
	@Column('estimated_ship_cost')
		@Column('actual_ship_cost')
		@Column('latest_cancel_date')
	DateTime latest_cancel_date;
	@Column('handling_instructions')
	String handling_instructions;
	@Column('last_updated')
	DateTime last_updated;

	// ***Table Foreign Key Entities***
	@Column.ManyToOneForeignKey('Address_id')
	Address address_from;
	@Column.ManyToOneForeignKey('Address_id1')
	Address address_to;
	@Column.ManyToOneForeignKey('Party_id')
	Party party_from;
	@Column.ManyToOneForeignKey('Party_id1')
	Party party_to;
	@Column.ManyToOneForeignKey('Phone_Number_id')
	Phone_Number phone_number;
	@Column.OneToManyForeignKey('Shipment_id')
	List<Outgoing_Shipment> outgoing_shipments;
	@Column.OneToManyForeignKey('Shipment_id')
	List<Incoming_Shipment> incoming_shipments;
	@Column.OneToManyForeignKey('Shipment_id')
	List<Transfer> transfers;
	@Column.OneToManyForeignKey('Shipment_id')
	List<Drop_Shipment> drop_shipments;
	@Column.OneToManyForeignKey('Shipment_id')
	List<Shipment_Item> shipment_items;
	@Column.OneToManyForeignKey('Shipment_id')
	List<Shipment_Status> shipment_statuss;
}
