/// Shipment_Receipt_Role_Type.dart
/// Version 0.0.1a
/// Copyright 2016 Programmers for a Better Tomorrow, Yesterday

part of entities;

/// Shipment_Receipt_Role_Type
/// This is an autogenerated class mapping the MySQL Table Shipment_Receipt_Role_Type to an AvacadORM Entity.

/// List of Shipment Receipt Role Types, for linking to from Shipment_Receipt_Role.
@Table('Shipment_Receipt_Role_Type')
class Shipment_Receipt_Role_Type extends Entity {
	// ***Table Columns***
	@Column.PrimaryKey('id')
	int id;
	@Column('description')
	String description;

	// ***Table Foreign Key Entities***
	@Column.OneToManyForeignKey('Shipment_Receipt_Role_Type_id')
	List<Shipment_Receipt_Role> shipment_receipt_roles;
}