/// Shipment_Package.dart
/// Version 0.0.1a
/// Copyright 2016 Programmers for a Better Tomorrow, Yesterday

part of entities;

/// Shipment_Package
/// This is an autogenerated class mapping the MySQL Table Shipment_Package to an AvacadORM Entity.

/// All shipments come in "Packages", even if that package is the single item. This is a list of packages that receipts can belong to. It is associated with an arbitrary number of Shipment_Receipts and Shipment_Items, ideally matching ones.
@Table('Shipment_Package')
class Shipment_Package extends Entity {
	// ***Table Columns***
	@Column.PrimaryKey('id')
	int id;
	@Column('date_created')
	DateTime date_created;

	// ***Table Foreign Key Entities***
	@Column.OneToManyForeignKey('Shipment_Package_id')
	List<Shipment_Receipt> shipment_receipts;
	@Column.OneToManyForeignKey('Shipment_Package_id')
	List<Packaging_Content> packaging_contents;
}