/// Shipment_Receipt_Role.dart
/// Version 0.0.1a
/// Copyright 2016 Programmers for a Better Tomorrow, Yesterday

part of entities;

/// Shipment_Receipt_Role
/// This is an autogenerated class mapping the MySQL Table Shipment_Receipt_Role to an AvacadORM Entity.

/// We can associate parties with the Shipment_Receipt entity in various arbitrary roles. This associates the three tables.
@Table('Shipment_Receipt_Role')
class Shipment_Receipt_Role extends Entity {
	// ***Table Columns***
	@Column.PrimaryKey('id')
	int id;
	@Column('Party_id')
	int Party_id;
	@Column('Shipment_Receipt_id')
	int Shipment_Receipt_id;
	@Column('Shipment_Receipt_Role_Type_id')
	int Shipment_Receipt_Role_Type_id;

	// ***Table Foreign Key Entities***
	@Column.ManyToOneForeignKey('Shipment_Receipt_id')
	Shipment_Receipt shipment_receipt;
	@Column.ManyToOneForeignKey('Shipment_Receipt_Role_Type_id')
	Shipment_Receipt_Role_Type shipment_receipt_role_type;
	@Column.ManyToOneForeignKey('Party_id')
	Party party;
}