/// Shipment_Item.dart
/// Version 0.0.1a
/// Copyright 2016 Programmers for a Better Tomorrow, Yesterday

part of entities;

/// Shipment_Item
/// This is an autogenerated class mapping the MySQL Table Shipment_Item to an AvacadORM Entity.

/// When tracking shipments, we want to know what to expect in a given shipment. Shipment_Item entities store information on the contents of shipments. If the item being shipped is already a Good in our system, we fill Good_id. Otherwise, we describe the product in shipment_contents_description. If an item is shipped more than once, we can link the newer Shipment_Item to the older one, to keep track of unique items on multiple shipments.
@Table('Shipment_Item')
class Shipment_Item extends Entity {
	// ***Table Columns***
	@Column.PrimaryKey('id')
	int id;
	@Column('Good_id')
	int Good_id;
	@Column('Shipment_id')
	int Shipment_id;
	@Column('in_response_to')
	int in_response_to;
	@Column('quantity')
	int quantity;
	@Column('shipment_contents_description')
	String shipment_contents_description;

	// ***Table Foreign Key Entities***
	@Column.ManyToOneForeignKey('Good_id')
	Good good;
	@Column.ManyToOneForeignKey('Shipment_id')
	Shipment shipment;
	@Column.ManyToOneForeignKey('in_response_to')
	Shipment_Item shipment_item;
	@Column.OneToManyForeignKey('in_response_to')
	List<Shipment_Item> shipment_items;
	@Column.OneToManyForeignKey('Shipment_Item_id')
	List<Order_Shipment> order_shipments;
	@Column.OneToManyForeignKey('Shipment_Item_id')
	List<Shipment_Item_Feature> shipment_item_features;
	@Column.OneToManyForeignKey('Shipment_Item_id')
	List<Packaging_Content> packaging_contents;
	@Column.OneToManyForeignKey('Shipment_Item_id')
	List<Item_Issuance> item_issuances;
}