/// Shipping_and_Handling.dart
/// Version 0.0.1a
/// Copyright 2016 Programmers for a Better Tomorrow, Yesterday

part of entities;

/// Shipping_and_Handling
/// This is an autogenerated class mapping the MySQL Table Shipping_and_Handling to an AvacadORM Entity.

/// Subclass of Order_Adjustment, this adjustment is due to Shipping & Handling.
@Table('Shipping_and_Handling')
class Shipping_and_Handling extends Entity {
	// ***Table Columns***
	@Column.PrimaryKey('id')
	int id;
	@Column('Order_Adjustment_id')
	int Order_Adjustment_id;

	// ***Table Foreign Key Entities***
	@Column.ManyToOneForeignKey('Order_Adjustment_id')
	Order_Adjustment order_adjustment;
}