/// SKU.dart
/// Version 0.0.1a
/// Copyright 2016 Programmers for a Better Tomorrow, Yesterday

part of entities;

/// SKU
/// This is an autogenerated class mapping the MySQL Table SKU to an AvacadORM Entity.

/// List of SKUs that should return the linked Good.
@Table('SKU')
class SKU extends Entity {
	// ***Table Columns***
	@Column.PrimaryKey('id')
	int id;
	@Column('Good_Identification_id')
	int Good_Identification_id;
	@Column('sku_id')
	String sku_id;

	// ***Table Foreign Key Entities***
	@Column.ManyToOneForeignKey('Good_Identification_id')
	Good_Identification good_identification;
}