/// Supplier_Product.dart
/// Version 0.0.1a
/// Copyright 2016 Programmers for a Better Tomorrow, Yesterday

part of entities;

/// Supplier_Product
/// This is an autogenerated class mapping the MySQL Table Supplier_Product to an AvacadORM Entity.

/// Association of Organizations and Products, representing a relationship with the organization as a supplier of the product. Has date ranges to designate the time the product is available from that organization, as well as lead time, to tell you how long it generally takes to receive reorders of the product.
@Table('Supplier_Product')
class Supplier_Product extends Entity {
	// ***Table Columns***
	@Column.PrimaryKey('id')
	int id;
	@Column('Product_id')
	int Product_id;
	@Column('Organization_id')
	int Organization_id;
	@Column('from_date')
	DateTime from_date;
	@Column('thru_date')
	DateTime thru_date;
	@Column('standard_lead_time')
	String standard_lead_time;
	@Column('comment')
	String comment;

	// ***Table Foreign Key Entities***
	@Column.ManyToOneForeignKey('Product_id')
	Product product;
	@Column.ManyToOneForeignKey('Organization_id')
	Organization organization;
}