/// Transfer.dart
/// Version 0.0.1a
/// Copyright 2016 Programmers for a Better Tomorrow, Yesterday

part of entities;

/// Transfer
/// This is an autogenerated class mapping the MySQL Table Transfer to an AvacadORM Entity.

/// Subclass of Shipment, representing transfer of goods within the business.
@Table('Transfer')
class Transfer extends Entity {
	// ***Table Columns***
	@Column.PrimaryKey('id')
	int id;
	@Column('Shipment_id')
	int Shipment_id;

	// ***Table Foreign Key Entities***
	@Column.ManyToOneForeignKey('Shipment_id')
	Shipment shipment;
}